// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztifzsodvqrrnrjbeaod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0aWZ6c29kdnFycm5yamJlYW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3Nzc2NjgsImV4cCI6MjA1NTM1MzY2OH0.VW5Mpq861b2aOiCzmtfWje9fHzVGArIOQUGKAzeDvHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'x-timeout-seconds': '30'
      }
    }
  }
);
